env: "local" # dev, prod
secret_key: "d9458a559557d448648c9a513a995d27" # generated
storage_path: "./storage/storage.db"
http_server:
  address: ":8080"
  timeout: "4s"
  idle_timeout: "60s"
  user: "user"
  password: "password"
